/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\1997_toyota_castrol_toms_supra.glb 
Author: Dave Bored SketchFab (https://sketchfab.com/Tyler_Dave)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1997-toyota-castrol-toms-supra-65596d3e409b4741a8c93349e8efc37b
Title: 1997 Toyota Castrol TOM'S Supra
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/1997_toyota_castrol_toms_supra.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 3.126]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-5.655, -0.191, -5.015]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Mesheswindow101Mtl} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Meshesunderbody231Mtl} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.Meshesrrea11Mtl} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.Meshesmirrors151Mtl} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.Mesheslight1151Mtl} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.Mesheslight141Mtl} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.Mesheshatch1Mtl} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.Meshesdash161Mtl} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.Meshescage11Mtl} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.Meshesbody101Mtl} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.Meshesbanner31Mtl} />
          </group>
          <group position={[-5.655, -0.191, -5.015]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh geometry={nodes.Object_16.geometry} material={materials.Meshestire1221Mtl} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.Meshesrim2151Mtl} />
          </group>
          <group position={[-5.655, -0.191, -5.015]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh geometry={nodes.Object_19.geometry} material={materials.Meshesrim3141Mtl} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.Meshestire201Mtl} />
          </group>
          <group position={[-5.655, -0.191, 3.031]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh geometry={nodes.Object_22.geometry} material={materials['Meshesrim3141Mtl.001']} />
            <mesh geometry={nodes.Object_23.geometry} material={materials['Meshestire201Mtl.001']} />
          </group>
          <group position={[-5.655, -0.191, 3.031]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh geometry={nodes.Object_25.geometry} material={materials['Meshestire1221Mtl.001']} />
            <mesh geometry={nodes.Object_26.geometry} material={materials['Meshesrim2151Mtl.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/1997_toyota_castrol_toms_supra.glb')
