/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\2018_acura_nsx_gt3.glb 
Author: OUTPISTON (https://sketchfab.com/outpiston)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2018-acura-nsx-gt3-72b01db86f9d462aa6666d2882b69ed2
Title: 2018 Acura NSX GT3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/2018_acura_nsx_gt3.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.017, 0.335, 1.226]} rotation={[Math.PI / 2, 0, 0]} scale={[-1, 1.114, 1.114]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.LOD_A_BRAKE_CALIPER_FRONT_LEFT_mm_misc_Mat} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.LOD_A_TYRE_mm_tyre_Mat} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.LOD_A_ROTOR_mm_rotor_Mat} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.LOD_A_BRAKE_CALIPER_REAR_LEFT_mm_misc_Mat} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.LOD_A_WHEEL_mm_wheel_Mat} />
      </group>
      <group position={[-1.017, 0.348, -1.401]} rotation={[Math.PI / 2, 0, 0]} scale={[-1, 1.156, 1.156]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.LOD_A_BRAKE_CALIPER_FRONT_LEFT_mm_misc_Mat} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.LOD_A_TYRE_mm_tyre_Mat} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.LOD_A_ROTOR_mm_rotor_Mat} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.LOD_A_BRAKE_CALIPER_REAR_LEFT_mm_misc_Mat} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.LOD_A_WHEEL_mm_wheel_Mat} />
      </group>
      <group position={[1.017, 0.348, -1.401]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1.156, 1.156]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.LOD_A_BRAKE_CALIPER_FRONT_LEFT_mm_misc_Mat} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.LOD_A_TYRE_mm_tyre_Mat} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.LOD_A_ROTOR_mm_rotor_Mat} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.LOD_A_BRAKE_CALIPER_REAR_LEFT_mm_misc_Mat} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.LOD_A_WHEEL_mm_wheel_Mat} />
      </group>
      <group position={[1.017, 0.335, 1.226]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1.114, 1.114]}>
        <mesh geometry={nodes.Object_96.geometry} material={materials.LOD_A_BRAKE_CALIPER_FRONT_LEFT_mm_misc_Mat} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.LOD_A_TYRE_mm_tyre_Mat} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.LOD_A_ROTOR_mm_rotor_Mat} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.LOD_A_BRAKE_CALIPER_REAR_LEFT_mm_misc_Mat} />
        <mesh geometry={nodes.Object_100.geometry} material={materials.LOD_A_WHEEL_mm_wheel_Mat} />
      </group>
      <mesh geometry={nodes.Object_22.geometry} material={materials.LOD_A_FRONTBUMPER_mm_misc_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.LOD_A_GLASS_RIGHT_QUARTER_mm_windows_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.LOD_A_HEADLIGHT_LENS_LEFT_mm_windows_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.LOD_A_CHASSIS_mm_chassis_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.LOD_A_TAILLIGHT_LENS_RIGHT_mm_windows_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.LOD_A_REARBUMPER_mm_ext_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.LOD_A_REARBUMPER_mm_lights_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.LOD_A_FRONTBUMPER_mm_chassis_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.LOD_A_BRAKES_RIGHT_mm_lights_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.LOD_A_BRAKES_LEFT_mm_lights_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.LOD_A_MIRROR_GLASS_RIGHT_mm_misc_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.LOD_A_MIRROR_RIGHT_mm_ext_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.LOD_A_CHASSIS_mm_misc_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.LOD_A_DOOR_RIGHT_mm_cab_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.LOD_A_REARBUMPER_mm_badges_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.LOD_A_BRAKES_REARBUMPER_mm_lights_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.LOD_A_BOOT_mm_ext_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.LOD_A_EXHAUST_mm_ext_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.LOD_A_DOOR_RIGHT_mm_ext_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.LOD_A_REARBUMPER_mm_chassis_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.LOD_A_FRONTBUMPER_mm_ext_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.LOD_A_BODY_mm_ext_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.LOD_A_BOOT_mm_badges_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.LOD_A_BODY_mm_badges_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.LOD_A_MIRROR_RIGHT_mm_misc_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.LOD_A_GLASS_FRONT_mm_windows_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.LOD_A_DOOR_LEFT_mm_ext_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.LOD_A_STEERING_WHEEL_mm_cab_Mat} position={[0.343, 0.695, 0.314]} rotation={[1.873, 0, 0]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.LOD_A_MIRROR_GLASS_LEFT_mm_misc_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.LOD_A_BODY_mm_chassis_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.LOD_A_DOOR_RIGHT_mm_misc_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.LOD_A_REARBUMPER_mm_misc_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.LOD_A_MIRROR_LEFT_mm_ext_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.LOD_A_BOOT_mm_misc_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.LOD_A_HOOD_mm_ext_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.LOD_A_TAILLIGHT_LENS_LEFT_mm_windows_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.LOD_A_HEADLIGHT_LENS_RIGHT_mm_windows_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.LOD_A_MIRROR_LEFT_mm_misc_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.LOD_A_DOOR_LEFT_mm_misc_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.LOD_A_DOOR_LEFT_mm_cab_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.LOD_A_INTERIOR_mm_cab_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.LOD_A_HOOD_mm_badges_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.LOD_A_FRONTBUMPER_mm_badges_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.LOD_A_BODY_mm_misc_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.LOD_A_HOOD_mm_misc_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.LOD_A_BODY_mm_lights_Mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.LOD_A_GLASS_LEFT_QUARTER_mm_windows_Mat} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/2018_acura_nsx_gt3.glb')
